project:
  type: website
  output-dir: docs

execute: 
  freeze: auto
website:
  title: ""
  navbar:
    logo: files/img/brandlogoone.png
    left:
      - about.qmd
    right: 
      - href: Apps_Projects/index.qmd
        text: apps & projects
        icon: boxes
      - href: Workshops_Conferences/index.qmd
        text: workshops & conferences
        icon: airplane
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

