project:
  type: website
  output-dir: docs

execute: 
  freeze: auto
website:
  title: "Shey Dorji"
  navbar:
    left:
      - about.qmd
    right: 
      - href: Apps_Projects/index.qmd
        text: Apps & Projects
        icon: boxes
format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true



